# Generated by Django 3.1.13 on 2021-08-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockname',
            field=models.CharField(max_length=50),
        ),
    ]
