# Generated by Django 3.1.13 on 2021-09-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210811_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='제목')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('link', models.URLField(verbose_name='링크 주소')),
                ('created_at', models.DateField(verbose_name='작성일')),
                ('company', models.CharField(choices=[(1, '미래에셋대우'), (2, 'KB')], max_length=1)),
            ],
        ),
    ]
