# Generated by Django 3.1.13 on 2021-09-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210911_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
