# Generated by Django 3.1.13 on 2021-09-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210911_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='documentid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
