# Generated by Django 3.1.13 on 2022-02-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_research_documentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='outstandingShare',
            field=models.IntegerField(default=0),
        ),
    ]
