# Generated by Django 3.1.13 on 2022-02-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participant_stock',
            field=models.IntegerField(default=0),
        ),
    ]
