# Generated by Django 3.1.13 on 2021-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_1',
            field=models.BooleanField(default=False, verbose_name='개인정보처리방침 동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_change',
            field=models.BooleanField(default=False, verbose_name='이름 변경'),
        ),
    ]
