# Generated by Django 3.1.13 on 2021-09-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210810_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_change',
        ),
    ]
